# Server
server.port=8080

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/bank-management
spring.datasource.username=postgres
spring.datasource.password=TANUJA
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
bank.app.jwtSecret=7zS3eK9pQ2rT6wY1uI5oA8dF4gH0jL2nM5bV7cX9zR1tY3uI6oP9aD2eG4hJ6kL8
bank.app.jwtExpirationMs=86400000

# Logging
logging.level.org.springframework.security=DEBUG